export const ghlShowcase = {
  kicker: "Live work",
  title: "Real GoHighLevel, not a demo.",
  lede: "This is a live CRM we set up and ran. Names and numbers are hidden. The pipelines, follow-up, and reporting are the real thing — thousands of people moving through stages, not a sample file.",
  note: "Client names, messages, and phone numbers were removed. Pipeline values are not claimed as cash collected.",
  stats: [
    { value: "2,480", label: "People in one sales pipeline" },
    { value: "440", label: "People tracked through a client journey" },
    { value: "2,085", label: "Leads that arrived automatically" },
    { value: "3", label: "Business numbers ready for texts and calls" },
  ],
  steps: [
    { n: "01", title: "Map the stages", body: "What happens after someone enquires, and who owns the next step." },
    { n: "02", title: "Build the CRM", body: "Contacts, pipelines, and sources so the team is not living in a spreadsheet." },
    { n: "03", title: "Turn on follow-up", body: "Texts and emails that go out on a timer, with a backup path if something is missing." },
    { n: "04", title: "Test, then go live", body: "Check the odd cases, publish, and watch the numbers so nothing sits untouched." },
  ],
  shots: [
    {
      src: "/work/cover.jpg",
      width: 1280,
      height: 687,
      alt: "GoHighLevel opportunities overview from a live account",
      caption: "A live opportunities view — volume you can manage, not a five-row demo.",
      featured: true,
    },
    {
      src: "/work/pipeline-journey.jpg",
      width: 1400,
      height: 982,
      alt: "GoHighLevel client journey pipeline with trial and enrolled stages",
      caption: "A client journey: trial, attended, pending, enrolled — so staff can see what to do next.",
    },
    {
      src: "/work/pipeline-sales.jpg",
      width: 1280,
      height: 687,
      alt: "GoHighLevel sales pipeline organised by contact status",
      caption: "A high-volume sales board: new, attempted, contacted, in conversation — 2,480 people, not a messy list.",
    },
    {
      src: "/work/reporting.jpg",
      width: 1280,
      height: 726,
      alt: "GoHighLevel opportunity reporting by pipeline stage",
      caption: "A manager view: where people pile up, so follow-up gets aimed at the bottleneck.",
    },
    {
      src: "/work/workflows.jpg",
      width: 1400,
      height: 796,
      alt: "Published GoHighLevel workflows for API intake and visitor follow-up",
      caption: "Published workflows: leads enter from the website or an API and immediately qualify for follow-up.",
    },
    {
      src: "/work/follow-up.jpg",
      width: 1400,
      height: 631,
      alt: "GoHighLevel workflow with timed SMS and email branches",
      caption: "Follow-up that branches: wait, text, email, try again — not one blast and silence.",
    },
    {
      src: "/work/phone.jpg",
      width: 1400,
      height: 502,
      alt: "GoHighLevel phone and A2P 10DLC messaging setup",
      caption: "Phone and SMS set up properly, including A2P 10DLC, so texts actually send.",
    },
  ],
  outcomes: [
    "Faster first reply — the CRM starts follow-up as soon as the lead arrives.",
    "A clear next action for the team, even when volume is high.",
    "Less copy-paste between tools. Intake, messages, and stages live in one place.",
  ],
} as const;
